apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
