apiVersion: v1
kind: Pod
metadata:
  name: simple-job-$i
spec:
  restartPolicy: Never
  containers:
  - name: simplejob-container
    image: abesharphpe/s3wordcountjob:01
    env:
    - name: S3_BUCKET
      value: "data"
    - name: S3_FILENAME
      value: "war-and-peace.txt"
    - name: S3_ENDPOINT_URL
      value: "http://objectstore-minio:9000"
    - name: S3_ACCESS_KEY
      value: "admin"
    - name: S3_SECRET_KEY
      value: "6XRyD5cpwo"
    resources:
      requests:
        memory: "64Mi"
        cpu: "2"
      limits:
        memory: "128Mi"
        cpu: "4"
